default:
    command:
        history:
            filename: ../../cmdhist.pcap
    sequence:
        directory: ../../seq/
    cmddict:
        filename:  cmd.yaml

    evrdict:
        filename:  evr.yaml

    tlmdict:
        filename:  tlm.yaml

    limits:
        filename:  limits/limits.yaml
      
    table:
        filename: table.yaml

    bsc:
        filename: bsc.yaml

    dsn:
        sle:
            initiator_id: uname
            password: pw
            responder_id: uname
            peer_password: pw
        cfdp:
            mib:
                path: ./mib
            datasink:
                outgoing:
                    path: ../ait/dsn/cfdp/datasink/outgoing
                incoming:
                    path: ../ait/dsn/cfdp/datasink/incoming
                tempfiles:
                    path: ../ait/dsn/cfdp/datasink/tempfiles
                pdusink:
                    path: ../ait/dsn/cfdp/datasink/pdusink
            max_file_name_length: 64
            max_entity_id_length: 8
            max_transaction_id_length: 8

    logging:
        name: ait
        hostname: yourhostname.com

    phase: 'dev'

    data:
        '1553':
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/downlink/1553
        bad:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/downlink/bad
        lehx:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/downlink/lehx
        planning:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/planning
        sdos:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/sdos
        uplink:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/uplink
        ats:
            path: /gds/${phase}/data/${hostname}/%Y/%Y-%j/ats

    gui:
      port: 8080
      telemetry:
        - stream:
            name: 1553_HS_Packet
            port: 3076
